export const consentList = [
  {
    _id: {
      $oid: "64f83d325de5aefa66c181ef",
    },
    PatientHealthId: "gautam_1999@sbx",
    Visits: 0,
    LinkedHealthRecords: [
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "Arogya HIP linked",
        visit: 0,
        patientRefNumber: "GRwe!2",
        patientDisplay: "wed 6 test",
        careContextRefNumber: "wed 6 test",
        careContextDeisplay: "wed 6 test",
      },
      {
        Linked: "Arogya HIP linked",
        visit: 0,
        patientRefNumber: "Gautam rawat sep",
        patientDisplay: "Gautam rawat sep",
        careContextRefNumber: "Gautam rawat sep",
        careContextDeisplay: "Gautam rawat sep wed",
      },
      {
        Linked: "Arogya HIP linked",
        visit: 0,
        patientRefNumber: "gautamRawat12",
        patientDisplay: "gautamRawat",
        careContextRefNumber: "sep visit",
        careContextDeisplay: "sep visit",
      },
      {
        Linked: "Arogya HIP linked",
        visit: 0,
        patientRefNumber: "gautamRawat43",
        patientDisplay: "gautamRawat43",
        careContextRefNumber: "sep wed 6 2023 3",
        careContextDeisplay: "sep wed 6 2023 3",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "Not linked",
        visit: 0,
        patientRefNumber: "GARA1999",
        patientDisplay: "gautam Rawat",
        careContextRefNumber: "11 sep CC",
        careContextDeisplay: "11 sep cc test",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "PAT001",
        patientDisplay: "good patient",
        careContextRefNumber: "PAT001-visit",
        careContextDeisplay: "16Jan visit",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA1999",
        patientDisplay: "gautam Rawat",
        careContextRefNumber: "11 sep CC",
        careContextDeisplay: "11 sep cc test",
      },
      {
        Linked: "Not linked",
        visit: 0,
        patientRefNumber: "GARA19992",
        patientDisplay: "gautam Rawat2",
        careContextRefNumber: "11 sep CC2",
        careContextDeisplay: "11 sep cc test2",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA19993",
        patientDisplay: "gautam Rawat3",
        careContextRefNumber: "11 sep CC3",
        careContextDeisplay: "11 sep cc test3",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA19994",
        patientDisplay: "gautam Rawat4",
        careContextRefNumber: "11 sep CC4",
        careContextDeisplay: "11 sep cc test4",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA19995",
        patientDisplay: "gautam Rawat5",
        careContextRefNumber: "11 sep CC5",
        careContextDeisplay: "11 sep cc test5",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA1999",
        patientDisplay: "gautam Rawat7",
        careContextRefNumber: "11 sep CC7",
        careContextDeisplay: "11 sep cc test7",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA1999",
        patientDisplay: "gautam Rawat9",
        careContextRefNumber: "11 sep CC9",
        careContextDeisplay: "11 sep cc test9",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA1999",
        patientDisplay: "gautam Rawat9",
        careContextRefNumber: "11 sep CC9",
        careContextDeisplay: "11 sep cc test9",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA1999",
        patientDisplay: "gautam Rawat10",
        careContextRefNumber: "11 sep CC10",
        careContextDeisplay: "11 sep cc test10",
      },
      {
        Linked: "User Linked",
        visit: 0,
        patientRefNumber: "GARA1999",
        patientDisplay: "gautam Rawat10",
        careContextRefNumber: "11 sep CC11",
        careContextDeisplay: "11 sep cc test11",
      },
      {
        Linked: "Arogya HIP linked",
        visit: 0,
        patientRefNumber: "12Sep Wed test - OPD1",
        patientDisplay: "gautamRawatSep12",
        careContextRefNumber: "12Sep Wed test - OPD1",
        careContextDeisplay: "12Sep Wed test - OPD1",
      },
    ],
    __v: 0,
  },
];
